name: build rocksfs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install fuse
        run: |
          sudo apt install -y libfuse-dev libfuse3-dev build-essential
      - name: Cargo build
        run: |
          cargo build
          cargo test